#!/usr/bin/env bash

session=$(find ~/git/ ~/scripts/ ~/.config/ -mindepth 1 -maxdepth 2 -type d | fzf)

session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2>/dev/null; then
    tmux new-session -d -t "$session_name" -c "$session"
fi

tmux switch-client -t "$session_name"
